////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2013 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 5.20Release
// Tag = $Name: AKW5_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public class CapabilitiesMesg extends Mesg {


   public CapabilitiesMesg() {
      super(Factory.createMesg(MesgNum.CAPABILITIES));
   }

   public CapabilitiesMesg(final Mesg mesg) {
      super(mesg);
   }


   /**
    * @return number of languages
    */
   public int getNumLanguages() {
      return getNumFieldValues(0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get languages field
    * Comment: Use language_bits_x types where x is index of array.
    *
    * @param index of languages
    * @return languages
    */
   public Short getLanguages(int index) {
      return getFieldShortValue(0, index, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set languages field
    * Comment: Use language_bits_x types where x is index of array.
    *
    * @param index of languages
    * @param languages
    */
   public void setLanguages(int index, Short languages) {
      setFieldValue(0, index, languages, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * @return number of sports
    */
   public int getNumSports() {
      return getNumFieldValues(1, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get sports field
    * Comment: Use sport_bits_x types where x is index of array.
    *
    * @param index of sports
    * @return sports
    */
   public Short getSports(int index) {
      return getFieldShortValue(1, index, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set sports field
    * Comment: Use sport_bits_x types where x is index of array.
    *
    * @param index of sports
    * @param sports
    */
   public void setSports(int index, Short sports) {
      setFieldValue(1, index, sports, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get workouts_supported field
    *
    * @return workouts_supported
    */
   public Long getWorkoutsSupported() {
      return getFieldLongValue(21, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set workouts_supported field
    *
    * @param workoutsSupported
    */
   public void setWorkoutsSupported(Long workoutsSupported) {
      setFieldValue(21, 0, workoutsSupported, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

}
