////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2013 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 5.20Release
// Tag = $Name: AKW5_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

import java.util.ArrayList;

public class Factory {
   static public Mesg createMesg(Mesg mesg) {
      switch (mesg.getNum()) {       
         case MesgNum.FILE_ID:
            return new FileIdMesg(mesg);       
         case MesgNum.FILE_CREATOR:
            return new FileCreatorMesg(mesg);       
         case MesgNum.SOFTWARE:
            return new SoftwareMesg(mesg);       
         case MesgNum.CAPABILITIES:
            return new CapabilitiesMesg(mesg);       
         case MesgNum.FILE_CAPABILITIES:
            return new FileCapabilitiesMesg(mesg);       
         case MesgNum.MESG_CAPABILITIES:
            return new MesgCapabilitiesMesg(mesg);       
         case MesgNum.FIELD_CAPABILITIES:
            return new FieldCapabilitiesMesg(mesg);       
         case MesgNum.DEVICE_SETTINGS:
            return new DeviceSettingsMesg(mesg);       
         case MesgNum.USER_PROFILE:
            return new UserProfileMesg(mesg);       
         case MesgNum.HRM_PROFILE:
            return new HrmProfileMesg(mesg);       
         case MesgNum.SDM_PROFILE:
            return new SdmProfileMesg(mesg);       
         case MesgNum.BIKE_PROFILE:
            return new BikeProfileMesg(mesg);       
         case MesgNum.ZONES_TARGET:
            return new ZonesTargetMesg(mesg);       
         case MesgNum.SPORT:
            return new SportMesg(mesg);       
         case MesgNum.HR_ZONE:
            return new HrZoneMesg(mesg);       
         case MesgNum.SPEED_ZONE:
            return new SpeedZoneMesg(mesg);       
         case MesgNum.CADENCE_ZONE:
            return new CadenceZoneMesg(mesg);       
         case MesgNum.POWER_ZONE:
            return new PowerZoneMesg(mesg);       
         case MesgNum.MET_ZONE:
            return new MetZoneMesg(mesg);       
         case MesgNum.GOAL:
            return new GoalMesg(mesg);       
         case MesgNum.ACTIVITY:
            return new ActivityMesg(mesg);       
         case MesgNum.SESSION:
            return new SessionMesg(mesg);       
         case MesgNum.LAP:
            return new LapMesg(mesg);       
         case MesgNum.LENGTH:
            return new LengthMesg(mesg);       
         case MesgNum.RECORD:
            return new RecordMesg(mesg);       
         case MesgNum.EVENT:
            return new EventMesg(mesg);       
         case MesgNum.DEVICE_INFO:
            return new DeviceInfoMesg(mesg);       
         case MesgNum.HRV:
            return new HrvMesg(mesg);       
         case MesgNum.COURSE:
            return new CourseMesg(mesg);       
         case MesgNum.COURSE_POINT:
            return new CoursePointMesg(mesg);       
         case MesgNum.WORKOUT:
            return new WorkoutMesg(mesg);       
         case MesgNum.WORKOUT_STEP:
            return new WorkoutStepMesg(mesg);       
         case MesgNum.SCHEDULE:
            return new ScheduleMesg(mesg);       
         case MesgNum.TOTALS:
            return new TotalsMesg(mesg);       
         case MesgNum.WEIGHT_SCALE:
            return new WeightScaleMesg(mesg);       
         case MesgNum.BLOOD_PRESSURE:
            return new BloodPressureMesg(mesg);       
         case MesgNum.MONITORING_INFO:
            return new MonitoringInfoMesg(mesg);       
         case MesgNum.MONITORING:
            return new MonitoringMesg(mesg);       
         case MesgNum.PAD:
            return new PadMesg(mesg);
         default:
            break;
      }
      return new Mesg("unknown", MesgNum.INVALID);
   }

   static public Mesg createMesg(int mesgNum) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].num == mesgNum)
            return new Mesg(mesgs[i]);
      }
      return new Mesg("unknown", mesgNum);
   }

   static public Mesg createMesg(String mesgName) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].name.equals(mesgName))
            return new Mesg(mesgs[i]);
      }
      return new Mesg(mesgName, MesgNum.INVALID);
   }

   static public Field createField(String mesgName, String fieldName) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].name.equals(mesgName)) {
            return new Field(mesgs[i].getField(fieldName, false));
         }
      }
      return new Field(fieldName, Fit.FIELD_NUM_INVALID, 0, 1, 0, "");
   }

   static public Field createField(String mesgName, int fieldNum) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].name.equals(mesgName)) {
            return new Field(mesgs[i].getField(fieldNum));
         }
      }
      return new Field("unknown", fieldNum, 0, 1, 0, "");
   }

   static public Field createField(int mesgNum, int fieldNum) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].num == mesgNum) {
            return new Field(mesgs[i].getField(fieldNum));
         }
      }
      return new Field("unknown", fieldNum, 0, 1, 0, "");
   }

   static public Field createField(int mesgNum, String fieldName) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].num == mesgNum) {
            return new Field(mesgs[i].getField(fieldName, false));
         }
      }
      return new Field(fieldName, Fit.FIELD_NUM_INVALID, 0, 1, 0, "");
   }

   static public Field createField(String mesgName, String fieldName, ArrayList<Object> values) {
      Field field = createField(mesgName, fieldName);
      field.values = values;
      return field;
   }


   private static final	Mesg fileIdMesg;
   private static final	Mesg fileCreatorMesg;
   private static final	Mesg softwareMesg;
   private static final	Mesg capabilitiesMesg;
   private static final	Mesg fileCapabilitiesMesg;
   private static final	Mesg mesgCapabilitiesMesg;
   private static final	Mesg fieldCapabilitiesMesg;
   private static final	Mesg deviceSettingsMesg;
   private static final	Mesg userProfileMesg;
   private static final	Mesg hrmProfileMesg;
   private static final	Mesg sdmProfileMesg;
   private static final	Mesg bikeProfileMesg;
   private static final	Mesg zonesTargetMesg;
   private static final	Mesg sportMesg;
   private static final	Mesg hrZoneMesg;
   private static final	Mesg speedZoneMesg;
   private static final	Mesg cadenceZoneMesg;
   private static final	Mesg powerZoneMesg;
   private static final	Mesg metZoneMesg;
   private static final	Mesg goalMesg;
   private static final	Mesg activityMesg;
   private static final	Mesg sessionMesg;
   private static final	Mesg lapMesg;
   private static final	Mesg lengthMesg;
   private static final	Mesg recordMesg;
   private static final	Mesg eventMesg;
   private static final	Mesg deviceInfoMesg;
   private static final	Mesg hrvMesg;
   private static final	Mesg courseMesg;
   private static final	Mesg coursePointMesg;
   private static final	Mesg workoutMesg;
   private static final	Mesg workoutStepMesg;
   private static final	Mesg scheduleMesg;
   private static final	Mesg totalsMesg;
   private static final	Mesg weightScaleMesg;
   private static final	Mesg bloodPressureMesg;
   private static final	Mesg monitoringInfoMesg;
   private static final	Mesg monitoringMesg;
   private static final	Mesg padMesg;
   private static final Mesg mesgs[] = new Mesg[39];
 
   static {
      int mesg_index = 0;
      int field_index;
      int subfield_index;

      // file_id
      field_index = 0;
      fileIdMesg = new Mesg("file_id", MesgNum.FILE_ID);
      fileIdMesg.addField(new Field("type", 0, 0, 1, 0, ""));
      field_index++;
      fileIdMesg.addField(new Field("manufacturer", 1, 132, 1, 0, ""));
      field_index++;
      fileIdMesg.addField(new Field("product", 2, 132, 1, 0, ""));
      subfield_index = 0;
      fileIdMesg.fields.get(field_index).subFields.add(new SubField("garmin_product", 132, 1, 0, ""));
      fileIdMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 1);
      fileIdMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 15);
      fileIdMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 13);
      subfield_index++;
      field_index++;
      fileIdMesg.addField(new Field("serial_number", 3, 140, 1, 0, ""));
      field_index++;
      fileIdMesg.addField(new Field("time_created", 4, 134, 1, 0, ""));
      field_index++;
      fileIdMesg.addField(new Field("number", 5, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = fileIdMesg;
      mesg_index++;

      // file_creator
      field_index = 0;
      fileCreatorMesg = new Mesg("file_creator", MesgNum.FILE_CREATOR);
      fileCreatorMesg.addField(new Field("software_version", 0, 132, 1, 0, ""));
      field_index++;
      fileCreatorMesg.addField(new Field("hardware_version", 1, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = fileCreatorMesg;
      mesg_index++;

      // software
      field_index = 0;
      softwareMesg = new Mesg("software", MesgNum.SOFTWARE);
      softwareMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      softwareMesg.addField(new Field("version", 3, 132, 100, 0, ""));
      field_index++;
      softwareMesg.addField(new Field("part_number", 5, 7, 1, 0, ""));
      field_index++;
      softwareMesg.addField(new Field("manufacturer", 0, 132, 1, 0, ""));
      field_index++;
      softwareMesg.addField(new Field("product", 1, 132, 1, 0, ""));
      subfield_index = 0;
      softwareMesg.fields.get(field_index).subFields.add(new SubField("garmin_product", 132, 1, 0, ""));
      softwareMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 1);
      softwareMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 15);
      softwareMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 13);
      subfield_index++;
      field_index++;
      mesgs[mesg_index] = softwareMesg;
      mesg_index++;

      // capabilities
      field_index = 0;
      capabilitiesMesg = new Mesg("capabilities", MesgNum.CAPABILITIES);
      capabilitiesMesg.addField(new Field("languages", 0, 10, 1, 0, ""));
      field_index++;
      capabilitiesMesg.addField(new Field("sports", 1, 10, 1, 0, ""));
      field_index++;
      capabilitiesMesg.addField(new Field("workouts_supported", 21, 140, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = capabilitiesMesg;
      mesg_index++;

      // file_capabilities
      field_index = 0;
      fileCapabilitiesMesg = new Mesg("file_capabilities", MesgNum.FILE_CAPABILITIES);
      fileCapabilitiesMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      fileCapabilitiesMesg.addField(new Field("type", 0, 0, 1, 0, ""));
      field_index++;
      fileCapabilitiesMesg.addField(new Field("flags", 1, 10, 1, 0, ""));
      field_index++;
      fileCapabilitiesMesg.addField(new Field("directory", 2, 7, 1, 0, ""));
      field_index++;
      fileCapabilitiesMesg.addField(new Field("max_count", 3, 132, 1, 0, ""));
      field_index++;
      fileCapabilitiesMesg.addField(new Field("max_size", 4, 134, 1, 0, "bytes"));
      field_index++;
      mesgs[mesg_index] = fileCapabilitiesMesg;
      mesg_index++;

      // mesg_capabilities
      field_index = 0;
      mesgCapabilitiesMesg = new Mesg("mesg_capabilities", MesgNum.MESG_CAPABILITIES);
      mesgCapabilitiesMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgCapabilitiesMesg.addField(new Field("file", 0, 0, 1, 0, ""));
      field_index++;
      mesgCapabilitiesMesg.addField(new Field("mesg_num", 1, 132, 1, 0, ""));
      field_index++;
      mesgCapabilitiesMesg.addField(new Field("count_type", 2, 0, 1, 0, ""));
      field_index++;
      mesgCapabilitiesMesg.addField(new Field("count", 3, 132, 1, 0, ""));
      subfield_index = 0;
      mesgCapabilitiesMesg.fields.get(field_index).subFields.add(new SubField("num_per_file", 132, 1, 0, ""));
      mesgCapabilitiesMesg.fields.get(field_index).subFields.get(subfield_index).addMap(2, 0);
      subfield_index++;
      mesgCapabilitiesMesg.fields.get(field_index).subFields.add(new SubField("max_per_file", 132, 1, 0, ""));
      mesgCapabilitiesMesg.fields.get(field_index).subFields.get(subfield_index).addMap(2, 1);
      subfield_index++;
      mesgCapabilitiesMesg.fields.get(field_index).subFields.add(new SubField("max_per_file_type", 132, 1, 0, ""));
      mesgCapabilitiesMesg.fields.get(field_index).subFields.get(subfield_index).addMap(2, 2);
      subfield_index++;
      field_index++;
      mesgs[mesg_index] = mesgCapabilitiesMesg;
      mesg_index++;

      // field_capabilities
      field_index = 0;
      fieldCapabilitiesMesg = new Mesg("field_capabilities", MesgNum.FIELD_CAPABILITIES);
      fieldCapabilitiesMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      fieldCapabilitiesMesg.addField(new Field("file", 0, 0, 1, 0, ""));
      field_index++;
      fieldCapabilitiesMesg.addField(new Field("mesg_num", 1, 132, 1, 0, ""));
      field_index++;
      fieldCapabilitiesMesg.addField(new Field("field_num", 2, 2, 1, 0, ""));
      field_index++;
      fieldCapabilitiesMesg.addField(new Field("count", 3, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = fieldCapabilitiesMesg;
      mesg_index++;

      // device_settings
      field_index = 0;
      deviceSettingsMesg = new Mesg("device_settings", MesgNum.DEVICE_SETTINGS);
      deviceSettingsMesg.addField(new Field("utc_offset", 1, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = deviceSettingsMesg;
      mesg_index++;

      // user_profile
      field_index = 0;
      userProfileMesg = new Mesg("user_profile", MesgNum.USER_PROFILE);
      userProfileMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("friendly_name", 0, 7, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("gender", 1, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("age", 2, 2, 1, 0, "years"));
      field_index++;
      userProfileMesg.addField(new Field("height", 3, 2, 100, 0, "m"));
      field_index++;
      userProfileMesg.addField(new Field("weight", 4, 132, 10, 0, "kg"));
      field_index++;
      userProfileMesg.addField(new Field("language", 5, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("elev_setting", 6, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("weight_setting", 7, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("resting_heart_rate", 8, 2, 1, 0, "bpm"));
      field_index++;
      userProfileMesg.addField(new Field("default_max_running_heart_rate", 9, 2, 1, 0, "bpm"));
      field_index++;
      userProfileMesg.addField(new Field("default_max_biking_heart_rate", 10, 2, 1, 0, "bpm"));
      field_index++;
      userProfileMesg.addField(new Field("default_max_heart_rate", 11, 2, 1, 0, "bpm"));
      field_index++;
      userProfileMesg.addField(new Field("hr_setting", 12, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("speed_setting", 13, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("dist_setting", 14, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("power_setting", 16, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("activity_class", 17, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("position_setting", 18, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("temperature_setting", 21, 0, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("local_id", 22, 132, 1, 0, ""));
      field_index++;
      userProfileMesg.addField(new Field("global_id", 23, 13, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = userProfileMesg;
      mesg_index++;

      // hrm_profile
      field_index = 0;
      hrmProfileMesg = new Mesg("hrm_profile", MesgNum.HRM_PROFILE);
      hrmProfileMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      hrmProfileMesg.addField(new Field("enabled", 0, 0, 1, 0, ""));
      field_index++;
      hrmProfileMesg.addField(new Field("hrm_ant_id", 1, 139, 1, 0, ""));
      field_index++;
      hrmProfileMesg.addField(new Field("log_hrv", 2, 0, 1, 0, ""));
      field_index++;
      hrmProfileMesg.addField(new Field("hrm_ant_id_trans_type", 3, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = hrmProfileMesg;
      mesg_index++;

      // sdm_profile
      field_index = 0;
      sdmProfileMesg = new Mesg("sdm_profile", MesgNum.SDM_PROFILE);
      sdmProfileMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      sdmProfileMesg.addField(new Field("enabled", 0, 0, 1, 0, ""));
      field_index++;
      sdmProfileMesg.addField(new Field("sdm_ant_id", 1, 139, 1, 0, ""));
      field_index++;
      sdmProfileMesg.addField(new Field("sdm_cal_factor", 2, 132, 10, 0, "%"));
      field_index++;
      sdmProfileMesg.addField(new Field("odometer", 3, 134, 100, 0, "m"));
      field_index++;
      sdmProfileMesg.addField(new Field("speed_source", 4, 0, 1, 0, ""));
      field_index++;
      sdmProfileMesg.addField(new Field("sdm_ant_id_trans_type", 5, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = sdmProfileMesg;
      mesg_index++;

      // bike_profile
      field_index = 0;
      bikeProfileMesg = new Mesg("bike_profile", MesgNum.BIKE_PROFILE);
      bikeProfileMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("name", 0, 7, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("sport", 1, 0, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("sub_sport", 2, 0, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("odometer", 3, 134, 100, 0, "m"));
      field_index++;
      bikeProfileMesg.addField(new Field("bike_spd_ant_id", 4, 139, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("bike_cad_ant_id", 5, 139, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("bike_spdcad_ant_id", 6, 139, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("bike_power_ant_id", 7, 139, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("custom_wheelsize", 8, 132, 1000, 0, "m"));
      field_index++;
      bikeProfileMesg.addField(new Field("auto_wheelsize", 9, 132, 1000, 0, "m"));
      field_index++;
      bikeProfileMesg.addField(new Field("bike_weight", 10, 132, 10, 0, "kg"));
      field_index++;
      bikeProfileMesg.addField(new Field("power_cal_factor", 11, 132, 10, 0, "%"));
      field_index++;
      bikeProfileMesg.addField(new Field("auto_wheel_cal", 12, 0, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("auto_power_zero", 13, 0, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("id", 14, 2, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("spd_enabled", 15, 0, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("cad_enabled", 16, 0, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("spdcad_enabled", 17, 0, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("power_enabled", 18, 0, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("crank_length", 19, 2, 2, -110, "mm"));
      field_index++;
      bikeProfileMesg.addField(new Field("enabled", 20, 0, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("bike_spd_ant_id_trans_type", 21, 10, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("bike_cad_ant_id_trans_type", 22, 10, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("bike_spdcad_ant_id_trans_type", 23, 10, 1, 0, ""));
      field_index++;
      bikeProfileMesg.addField(new Field("bike_power_ant_id_trans_type", 24, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = bikeProfileMesg;
      mesg_index++;

      // zones_target
      field_index = 0;
      zonesTargetMesg = new Mesg("zones_target", MesgNum.ZONES_TARGET);
      zonesTargetMesg.addField(new Field("max_heart_rate", 1, 2, 1, 0, ""));
      field_index++;
      zonesTargetMesg.addField(new Field("threshold_heart_rate", 2, 2, 1, 0, ""));
      field_index++;
      zonesTargetMesg.addField(new Field("functional_threshold_power", 3, 132, 1, 0, ""));
      field_index++;
      zonesTargetMesg.addField(new Field("hr_calc_type", 5, 0, 1, 0, ""));
      field_index++;
      zonesTargetMesg.addField(new Field("pwr_calc_type", 7, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = zonesTargetMesg;
      mesg_index++;

      // sport
      field_index = 0;
      sportMesg = new Mesg("sport", MesgNum.SPORT);
      sportMesg.addField(new Field("sport", 0, 0, 1, 0, ""));
      field_index++;
      sportMesg.addField(new Field("sub_sport", 1, 0, 1, 0, ""));
      field_index++;
      sportMesg.addField(new Field("name", 3, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = sportMesg;
      mesg_index++;

      // hr_zone
      field_index = 0;
      hrZoneMesg = new Mesg("hr_zone", MesgNum.HR_ZONE);
      hrZoneMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      hrZoneMesg.addField(new Field("high_bpm", 1, 2, 1, 0, "bpm"));
      field_index++;
      hrZoneMesg.addField(new Field("name", 2, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = hrZoneMesg;
      mesg_index++;

      // speed_zone
      field_index = 0;
      speedZoneMesg = new Mesg("speed_zone", MesgNum.SPEED_ZONE);
      speedZoneMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      speedZoneMesg.addField(new Field("high_value", 0, 132, 1000, 0, "m/s"));
      field_index++;
      speedZoneMesg.addField(new Field("name", 1, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = speedZoneMesg;
      mesg_index++;

      // cadence_zone
      field_index = 0;
      cadenceZoneMesg = new Mesg("cadence_zone", MesgNum.CADENCE_ZONE);
      cadenceZoneMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      cadenceZoneMesg.addField(new Field("high_value", 0, 2, 1, 0, "rpm"));
      field_index++;
      cadenceZoneMesg.addField(new Field("name", 1, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = cadenceZoneMesg;
      mesg_index++;

      // power_zone
      field_index = 0;
      powerZoneMesg = new Mesg("power_zone", MesgNum.POWER_ZONE);
      powerZoneMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      powerZoneMesg.addField(new Field("high_value", 1, 132, 1, 0, "watts"));
      field_index++;
      powerZoneMesg.addField(new Field("name", 2, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = powerZoneMesg;
      mesg_index++;

      // met_zone
      field_index = 0;
      metZoneMesg = new Mesg("met_zone", MesgNum.MET_ZONE);
      metZoneMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      metZoneMesg.addField(new Field("high_bpm", 1, 2, 1, 0, ""));
      field_index++;
      metZoneMesg.addField(new Field("calories", 2, 132, 10, 0, "kcal / min"));
      field_index++;
      metZoneMesg.addField(new Field("fat_calories", 3, 2, 10, 0, "kcal / min"));
      field_index++;
      mesgs[mesg_index] = metZoneMesg;
      mesg_index++;

      // goal
      field_index = 0;
      goalMesg = new Mesg("goal", MesgNum.GOAL);
      goalMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("sport", 0, 0, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("sub_sport", 1, 0, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("start_date", 2, 134, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("end_date", 3, 134, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("type", 4, 0, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("value", 5, 134, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("repeat", 6, 0, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("target_value", 7, 134, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("recurrence", 8, 0, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("recurrence_value", 9, 132, 1, 0, ""));
      field_index++;
      goalMesg.addField(new Field("enabled", 10, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = goalMesg;
      mesg_index++;

      // activity
      field_index = 0;
      activityMesg = new Mesg("activity", MesgNum.ACTIVITY);
      activityMesg.addField(new Field("timestamp", 253, 134, 1, 0, ""));
      field_index++;
      activityMesg.addField(new Field("total_timer_time", 0, 134, 1000, 0, "s"));
      field_index++;
      activityMesg.addField(new Field("num_sessions", 1, 132, 1, 0, ""));
      field_index++;
      activityMesg.addField(new Field("type", 2, 0, 1, 0, ""));
      field_index++;
      activityMesg.addField(new Field("event", 3, 0, 1, 0, ""));
      field_index++;
      activityMesg.addField(new Field("event_type", 4, 0, 1, 0, ""));
      field_index++;
      activityMesg.addField(new Field("local_timestamp", 5, 134, 1, 0, ""));
      field_index++;
      activityMesg.addField(new Field("event_group", 6, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = activityMesg;
      mesg_index++;

      // session
      field_index = 0;
      sessionMesg = new Mesg("session", MesgNum.SESSION);
      sessionMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      sessionMesg.addField(new Field("event", 0, 0, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("event_type", 1, 0, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("start_time", 2, 134, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("start_position_lat", 3, 133, 1, 0, "semicircles"));
      field_index++;
      sessionMesg.addField(new Field("start_position_long", 4, 133, 1, 0, "semicircles"));
      field_index++;
      sessionMesg.addField(new Field("sport", 5, 0, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("sub_sport", 6, 0, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("total_elapsed_time", 7, 134, 1000, 0, "s"));
      field_index++;
      sessionMesg.addField(new Field("total_timer_time", 8, 134, 1000, 0, "s"));
      field_index++;
      sessionMesg.addField(new Field("total_distance", 9, 134, 100, 0, "m"));
      field_index++;
      sessionMesg.addField(new Field("total_cycles", 10, 134, 1, 0, "cycles"));
      subfield_index = 0;
      sessionMesg.fields.get(field_index).subFields.add(new SubField("total_strides", 134, 1, 0, "strides"));
      sessionMesg.fields.get(field_index).subFields.get(subfield_index).addMap(5, 1);
      subfield_index++;
      field_index++;
      sessionMesg.addField(new Field("total_calories", 11, 132, 1, 0, "kcal"));
      field_index++;
      sessionMesg.addField(new Field("total_fat_calories", 13, 132, 1, 0, "kcal"));
      field_index++;
      sessionMesg.addField(new Field("avg_speed", 14, 132, 1000, 0, "m/s"));
      field_index++;
      sessionMesg.addField(new Field("max_speed", 15, 132, 1000, 0, "m/s"));
      field_index++;
      sessionMesg.addField(new Field("avg_heart_rate", 16, 2, 1, 0, "bpm"));
      field_index++;
      sessionMesg.addField(new Field("max_heart_rate", 17, 2, 1, 0, "bpm"));
      field_index++;
      sessionMesg.addField(new Field("avg_cadence", 18, 2, 1, 0, "rpm"));
      subfield_index = 0;
      sessionMesg.fields.get(field_index).subFields.add(new SubField("avg_running_cadence", 2, 1, 0, "strides/min"));
      sessionMesg.fields.get(field_index).subFields.get(subfield_index).addMap(5, 1);
      subfield_index++;
      field_index++;
      sessionMesg.addField(new Field("max_cadence", 19, 2, 1, 0, "rpm"));
      subfield_index = 0;
      sessionMesg.fields.get(field_index).subFields.add(new SubField("max_running_cadence", 2, 1, 0, "strides/min"));
      sessionMesg.fields.get(field_index).subFields.get(subfield_index).addMap(5, 1);
      subfield_index++;
      field_index++;
      sessionMesg.addField(new Field("avg_power", 20, 132, 1, 0, "watts"));
      field_index++;
      sessionMesg.addField(new Field("max_power", 21, 132, 1, 0, "watts"));
      field_index++;
      sessionMesg.addField(new Field("total_ascent", 22, 132, 1, 0, "m"));
      field_index++;
      sessionMesg.addField(new Field("total_descent", 23, 132, 1, 0, "m"));
      field_index++;
      sessionMesg.addField(new Field("total_training_effect", 24, 2, 10, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("first_lap_index", 25, 132, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("num_laps", 26, 132, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("event_group", 27, 2, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("trigger", 28, 0, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("nec_lat", 29, 133, 1, 0, "semicircles"));
      field_index++;
      sessionMesg.addField(new Field("nec_long", 30, 133, 1, 0, "semicircles"));
      field_index++;
      sessionMesg.addField(new Field("swc_lat", 31, 133, 1, 0, "semicircles"));
      field_index++;
      sessionMesg.addField(new Field("swc_long", 32, 133, 1, 0, "semicircles"));
      field_index++;
      sessionMesg.addField(new Field("normalized_power", 34, 132, 1, 0, "watts"));
      field_index++;
      sessionMesg.addField(new Field("training_stress_score", 35, 132, 10, 0, "tss"));
      field_index++;
      sessionMesg.addField(new Field("intensity_factor", 36, 132, 1000, 0, "if"));
      field_index++;
      sessionMesg.addField(new Field("left_right_balance", 37, 132, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("avg_stroke_count", 41, 134, 10, 0, "strokes/lap"));
      field_index++;
      sessionMesg.addField(new Field("avg_stroke_distance", 42, 132, 100, 0, "m"));
      field_index++;
      sessionMesg.addField(new Field("swim_stroke", 43, 0, 1, 0, "swim_stroke"));
      field_index++;
      sessionMesg.addField(new Field("pool_length", 44, 132, 100, 0, "m"));
      field_index++;
      sessionMesg.addField(new Field("pool_length_unit", 46, 0, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("num_active_lengths", 47, 132, 1, 0, "lengths"));
      field_index++;
      sessionMesg.addField(new Field("total_work", 48, 134, 1, 0, "J"));
      field_index++;
      sessionMesg.addField(new Field("avg_altitude", 49, 132, 5, 500, "m"));
      field_index++;
      sessionMesg.addField(new Field("max_altitude", 50, 132, 5, 500, "m"));
      field_index++;
      sessionMesg.addField(new Field("gps_accuracy", 51, 2, 1, 0, "m"));
      field_index++;
      sessionMesg.addField(new Field("avg_grade", 52, 131, 100, 0, "%"));
      field_index++;
      sessionMesg.addField(new Field("avg_pos_grade", 53, 131, 100, 0, "%"));
      field_index++;
      sessionMesg.addField(new Field("avg_neg_grade", 54, 131, 100, 0, "%"));
      field_index++;
      sessionMesg.addField(new Field("max_pos_grade", 55, 131, 100, 0, "%"));
      field_index++;
      sessionMesg.addField(new Field("max_neg_grade", 56, 131, 100, 0, "%"));
      field_index++;
      sessionMesg.addField(new Field("avg_temperature", 57, 1, 1, 0, "C"));
      field_index++;
      sessionMesg.addField(new Field("max_temperature", 58, 1, 1, 0, "C"));
      field_index++;
      sessionMesg.addField(new Field("total_moving_time", 59, 134, 1000, 0, "s"));
      field_index++;
      sessionMesg.addField(new Field("avg_pos_vertical_speed", 60, 131, 1000, 0, "m/s"));
      field_index++;
      sessionMesg.addField(new Field("avg_neg_vertical_speed", 61, 131, 1000, 0, "m/s"));
      field_index++;
      sessionMesg.addField(new Field("max_pos_vertical_speed", 62, 131, 1000, 0, "m/s"));
      field_index++;
      sessionMesg.addField(new Field("max_neg_vertical_speed", 63, 131, 1000, 0, "m/s"));
      field_index++;
      sessionMesg.addField(new Field("min_heart_rate", 64, 2, 1, 0, "bpm"));
      field_index++;
      sessionMesg.addField(new Field("time_in_hr_zone", 65, 134, 1000, 0, "s"));
      field_index++;
      sessionMesg.addField(new Field("time_in_speed_zone", 66, 134, 1000, 0, "s"));
      field_index++;
      sessionMesg.addField(new Field("time_in_cadence_zone", 67, 134, 1000, 0, "s"));
      field_index++;
      sessionMesg.addField(new Field("time_in_power_zone", 68, 134, 1000, 0, "s"));
      field_index++;
      sessionMesg.addField(new Field("avg_lap_time", 69, 134, 1000, 0, "s"));
      field_index++;
      sessionMesg.addField(new Field("best_lap_index", 70, 132, 1, 0, ""));
      field_index++;
      sessionMesg.addField(new Field("min_altitude", 71, 132, 5, 500, "m"));
      field_index++;
      mesgs[mesg_index] = sessionMesg;
      mesg_index++;

      // lap
      field_index = 0;
      lapMesg = new Mesg("lap", MesgNum.LAP);
      lapMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      lapMesg.addField(new Field("event", 0, 0, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("event_type", 1, 0, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("start_time", 2, 134, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("start_position_lat", 3, 133, 1, 0, "semicircles"));
      field_index++;
      lapMesg.addField(new Field("start_position_long", 4, 133, 1, 0, "semicircles"));
      field_index++;
      lapMesg.addField(new Field("end_position_lat", 5, 133, 1, 0, "semicircles"));
      field_index++;
      lapMesg.addField(new Field("end_position_long", 6, 133, 1, 0, "semicircles"));
      field_index++;
      lapMesg.addField(new Field("total_elapsed_time", 7, 134, 1000, 0, "s"));
      field_index++;
      lapMesg.addField(new Field("total_timer_time", 8, 134, 1000, 0, "s"));
      field_index++;
      lapMesg.addField(new Field("total_distance", 9, 134, 100, 0, "m"));
      field_index++;
      lapMesg.addField(new Field("total_cycles", 10, 134, 1, 0, "cycles"));
      subfield_index = 0;
      lapMesg.fields.get(field_index).subFields.add(new SubField("total_strides", 134, 1, 0, "strides"));
      lapMesg.fields.get(field_index).subFields.get(subfield_index).addMap(25, 1);
      subfield_index++;
      field_index++;
      lapMesg.addField(new Field("total_calories", 11, 132, 1, 0, "kcal"));
      field_index++;
      lapMesg.addField(new Field("total_fat_calories", 12, 132, 1, 0, "kcal"));
      field_index++;
      lapMesg.addField(new Field("avg_speed", 13, 132, 1000, 0, "m/s"));
      field_index++;
      lapMesg.addField(new Field("max_speed", 14, 132, 1000, 0, "m/s"));
      field_index++;
      lapMesg.addField(new Field("avg_heart_rate", 15, 2, 1, 0, "bpm"));
      field_index++;
      lapMesg.addField(new Field("max_heart_rate", 16, 2, 1, 0, "bpm"));
      field_index++;
      lapMesg.addField(new Field("avg_cadence", 17, 2, 1, 0, "rpm"));
      subfield_index = 0;
      lapMesg.fields.get(field_index).subFields.add(new SubField("avg_running_cadence", 2, 1, 0, "strides/min"));
      lapMesg.fields.get(field_index).subFields.get(subfield_index).addMap(25, 1);
      subfield_index++;
      field_index++;
      lapMesg.addField(new Field("max_cadence", 18, 2, 1, 0, "rpm"));
      subfield_index = 0;
      lapMesg.fields.get(field_index).subFields.add(new SubField("max_running_cadence", 2, 1, 0, "strides/min"));
      lapMesg.fields.get(field_index).subFields.get(subfield_index).addMap(25, 1);
      subfield_index++;
      field_index++;
      lapMesg.addField(new Field("avg_power", 19, 132, 1, 0, "watts"));
      field_index++;
      lapMesg.addField(new Field("max_power", 20, 132, 1, 0, "watts"));
      field_index++;
      lapMesg.addField(new Field("total_ascent", 21, 132, 1, 0, "m"));
      field_index++;
      lapMesg.addField(new Field("total_descent", 22, 132, 1, 0, "m"));
      field_index++;
      lapMesg.addField(new Field("intensity", 23, 0, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("lap_trigger", 24, 0, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("sport", 25, 0, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("event_group", 26, 2, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("num_lengths", 32, 132, 1, 0, "lengths"));
      field_index++;
      lapMesg.addField(new Field("normalized_power", 33, 132, 1, 0, "watts"));
      field_index++;
      lapMesg.addField(new Field("left_right_balance", 34, 132, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("first_length_index", 35, 132, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("avg_stroke_distance", 37, 132, 100, 0, "m"));
      field_index++;
      lapMesg.addField(new Field("swim_stroke", 38, 0, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("sub_sport", 39, 0, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("num_active_lengths", 40, 132, 1, 0, "lengths"));
      field_index++;
      lapMesg.addField(new Field("total_work", 41, 134, 1, 0, "J"));
      field_index++;
      lapMesg.addField(new Field("avg_altitude", 42, 132, 5, 500, "m"));
      field_index++;
      lapMesg.addField(new Field("max_altitude", 43, 132, 5, 500, "m"));
      field_index++;
      lapMesg.addField(new Field("gps_accuracy", 44, 2, 1, 0, "m"));
      field_index++;
      lapMesg.addField(new Field("avg_grade", 45, 131, 100, 0, "%"));
      field_index++;
      lapMesg.addField(new Field("avg_pos_grade", 46, 131, 100, 0, "%"));
      field_index++;
      lapMesg.addField(new Field("avg_neg_grade", 47, 131, 100, 0, "%"));
      field_index++;
      lapMesg.addField(new Field("max_pos_grade", 48, 131, 100, 0, "%"));
      field_index++;
      lapMesg.addField(new Field("max_neg_grade", 49, 131, 100, 0, "%"));
      field_index++;
      lapMesg.addField(new Field("avg_temperature", 50, 1, 1, 0, "C"));
      field_index++;
      lapMesg.addField(new Field("max_temperature", 51, 1, 1, 0, "C"));
      field_index++;
      lapMesg.addField(new Field("total_moving_time", 52, 134, 1000, 0, "s"));
      field_index++;
      lapMesg.addField(new Field("avg_pos_vertical_speed", 53, 131, 1000, 0, "m/s"));
      field_index++;
      lapMesg.addField(new Field("avg_neg_vertical_speed", 54, 131, 1000, 0, "m/s"));
      field_index++;
      lapMesg.addField(new Field("max_pos_vertical_speed", 55, 131, 1000, 0, "m/s"));
      field_index++;
      lapMesg.addField(new Field("max_neg_vertical_speed", 56, 131, 1000, 0, "m/s"));
      field_index++;
      lapMesg.addField(new Field("time_in_hr_zone", 57, 134, 1000, 0, "s"));
      field_index++;
      lapMesg.addField(new Field("time_in_speed_zone", 58, 134, 1000, 0, "s"));
      field_index++;
      lapMesg.addField(new Field("time_in_cadence_zone", 59, 134, 1000, 0, "s"));
      field_index++;
      lapMesg.addField(new Field("time_in_power_zone", 60, 134, 1000, 0, "s"));
      field_index++;
      lapMesg.addField(new Field("repetition_num", 61, 132, 1, 0, ""));
      field_index++;
      lapMesg.addField(new Field("min_altitude", 62, 132, 5, 500, "m"));
      field_index++;
      lapMesg.addField(new Field("min_heart_rate", 63, 2, 1, 0, "bpm"));
      field_index++;
      lapMesg.addField(new Field("wkt_step_index", 71, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = lapMesg;
      mesg_index++;

      // length
      field_index = 0;
      lengthMesg = new Mesg("length", MesgNum.LENGTH);
      lengthMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      lengthMesg.addField(new Field("timestamp", 253, 134, 1, 0, ""));
      field_index++;
      lengthMesg.addField(new Field("event", 0, 0, 1, 0, ""));
      field_index++;
      lengthMesg.addField(new Field("event_type", 1, 0, 1, 0, ""));
      field_index++;
      lengthMesg.addField(new Field("start_time", 2, 134, 1, 0, ""));
      field_index++;
      lengthMesg.addField(new Field("total_elapsed_time", 3, 134, 1000, 0, "s"));
      field_index++;
      lengthMesg.addField(new Field("total_timer_time", 4, 134, 1000, 0, "s"));
      field_index++;
      lengthMesg.addField(new Field("total_strokes", 5, 132, 1, 0, "strokes"));
      field_index++;
      lengthMesg.addField(new Field("avg_speed", 6, 132, 1000, 0, "m/s"));
      field_index++;
      lengthMesg.addField(new Field("swim_stroke", 7, 0, 1, 0, "swim_stroke"));
      field_index++;
      lengthMesg.addField(new Field("avg_swimming_cadence", 9, 2, 1, 0, "strokes/min"));
      field_index++;
      lengthMesg.addField(new Field("event_group", 10, 2, 1, 0, ""));
      field_index++;
      lengthMesg.addField(new Field("total_calories", 11, 132, 1, 0, "kcal"));
      field_index++;
      lengthMesg.addField(new Field("length_type", 12, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = lengthMesg;
      mesg_index++;

      // record
      field_index = 0;
      recordMesg = new Mesg("record", MesgNum.RECORD);
      recordMesg.addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      recordMesg.addField(new Field("position_lat", 0, 133, 1, 0, "semicircles"));
      field_index++;
      recordMesg.addField(new Field("position_long", 1, 133, 1, 0, "semicircles"));
      field_index++;
      recordMesg.addField(new Field("altitude", 2, 132, 5, 500, "m"));
      field_index++;
      recordMesg.addField(new Field("heart_rate", 3, 2, 1, 0, "bpm"));
      field_index++;
      recordMesg.addField(new Field("cadence", 4, 2, 1, 0, "rpm"));
      field_index++;
      recordMesg.addField(new Field("distance", 5, 134, 100, 0, "m"));
      field_index++;
      recordMesg.addField(new Field("speed", 6, 132, 1000, 0, "m/s"));
      field_index++;
      recordMesg.addField(new Field("power", 7, 132, 1, 0, "watts"));
      field_index++;
      recordMesg.addField(new Field("compressed_speed_distance", 8, 13, 1, 0, "")); 
      recordMesg.fields.get(field_index).components.add(new FieldComponent(6, false, 12, 100, 0)); // speed 
      recordMesg.fields.get(field_index).components.add(new FieldComponent(5, true, 12, 16, 0)); // distance
      field_index++;
      recordMesg.addField(new Field("grade", 9, 131, 100, 0, "%"));
      field_index++;
      recordMesg.addField(new Field("resistance", 10, 2, 1, 0, ""));
      field_index++;
      recordMesg.addField(new Field("time_from_course", 11, 133, 1000, 0, "s"));
      field_index++;
      recordMesg.addField(new Field("cycle_length", 12, 2, 100, 0, "m"));
      field_index++;
      recordMesg.addField(new Field("temperature", 13, 1, 1, 0, "C"));
      field_index++;
      recordMesg.addField(new Field("speed_1s", 17, 2, 16, 0, "m/s"));
      field_index++;
      recordMesg.addField(new Field("cycles", 18, 2, 1, 0, "")); 
      recordMesg.fields.get(field_index).components.add(new FieldComponent(19, true, 8, 1, 0)); // total_cycles
      field_index++;
      recordMesg.addField(new Field("total_cycles", 19, 134, 1, 0, "cycles"));
      field_index++;
      recordMesg.addField(new Field("compressed_accumulated_power", 28, 132, 1, 0, "")); 
      recordMesg.fields.get(field_index).components.add(new FieldComponent(29, true, 16, 1, 0)); // accumulated_power
      field_index++;
      recordMesg.addField(new Field("accumulated_power", 29, 134, 1, 0, "watts"));
      field_index++;
      recordMesg.addField(new Field("left_right_balance", 30, 2, 1, 0, ""));
      field_index++;
      recordMesg.addField(new Field("gps_accuracy", 31, 2, 1, 0, "m"));
      field_index++;
      recordMesg.addField(new Field("vertical_speed", 32, 131, 1000, 0, "m/s"));
      field_index++;
      recordMesg.addField(new Field("calories", 33, 132, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index] = recordMesg;
      mesg_index++;

      // event
      field_index = 0;
      eventMesg = new Mesg("event", MesgNum.EVENT);
      eventMesg.addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      eventMesg.addField(new Field("event", 0, 0, 1, 0, ""));
      field_index++;
      eventMesg.addField(new Field("event_type", 1, 0, 1, 0, ""));
      field_index++;
      eventMesg.addField(new Field("data16", 2, 132, 1, 0, "")); 
      eventMesg.fields.get(field_index).components.add(new FieldComponent(3, false, 16, 1, 0)); // data
      field_index++;
      eventMesg.addField(new Field("data", 3, 134, 1, 0, ""));
      subfield_index = 0;
      eventMesg.fields.get(field_index).subFields.add(new SubField("timer_trigger", 0, 1, 0, ""));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 0);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("course_point_index", 132, 1, 0, ""));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 10);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("battery_level", 132, 1000, 0, "V"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 11);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("virtual_partner_speed", 132, 1000, 0, "m/s"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 12);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("hr_high_alert", 2, 1, 0, "bpm"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 13);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("hr_low_alert", 2, 1, 0, "bpm"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 14);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("speed_high_alert", 132, 1000, 0, "m/s"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 15);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("speed_low_alert", 132, 1000, 0, "m/s"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 16);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("cad_high_alert", 132, 1, 0, "rpm"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 17);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("cad_low_alert", 132, 1, 0, "rpm"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 18);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("power_high_alert", 132, 1, 0, "watts"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 19);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("power_low_alert", 132, 1, 0, "watts"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 20);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("time_duration_alert", 134, 1000, 0, "s"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 23);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("distance_duration_alert", 134, 100, 0, "m"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 24);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("calorie_duration_alert", 134, 1, 0, "calories"));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 25);
      subfield_index++;
      eventMesg.fields.get(field_index).subFields.add(new SubField("fitness_equipment_state", 0, 1, 0, ""));
      eventMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 27);
      subfield_index++;
      field_index++;
      eventMesg.addField(new Field("event_group", 4, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = eventMesg;
      mesg_index++;

      // device_info
      field_index = 0;
      deviceInfoMesg = new Mesg("device_info", MesgNum.DEVICE_INFO);
      deviceInfoMesg.addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      deviceInfoMesg.addField(new Field("device_index", 0, 2, 1, 0, ""));
      field_index++;
      deviceInfoMesg.addField(new Field("device_type", 1, 2, 1, 0, ""));
      field_index++;
      deviceInfoMesg.addField(new Field("manufacturer", 2, 132, 1, 0, ""));
      field_index++;
      deviceInfoMesg.addField(new Field("serial_number", 3, 140, 1, 0, ""));
      field_index++;
      deviceInfoMesg.addField(new Field("product", 4, 132, 1, 0, ""));
      field_index++;
      deviceInfoMesg.addField(new Field("software_version", 5, 132, 100, 0, ""));
      field_index++;
      deviceInfoMesg.addField(new Field("hardware_version", 6, 2, 1, 0, ""));
      field_index++;
      deviceInfoMesg.addField(new Field("cum_operating_time", 7, 134, 1, 0, "s"));
      field_index++;
      deviceInfoMesg.addField(new Field("battery_voltage", 10, 132, 256, 0, "V"));
      field_index++;
      deviceInfoMesg.addField(new Field("battery_status", 11, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = deviceInfoMesg;
      mesg_index++;

      // hrv
      field_index = 0;
      hrvMesg = new Mesg("hrv", MesgNum.HRV);
      hrvMesg.addField(new Field("time", 0, 132, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index] = hrvMesg;
      mesg_index++;

      // course
      field_index = 0;
      courseMesg = new Mesg("course", MesgNum.COURSE);
      courseMesg.addField(new Field("sport", 4, 0, 1, 0, ""));
      field_index++;
      courseMesg.addField(new Field("name", 5, 7, 1, 0, ""));
      field_index++;
      courseMesg.addField(new Field("capabilities", 6, 140, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = courseMesg;
      mesg_index++;

      // course_point
      field_index = 0;
      coursePointMesg = new Mesg("course_point", MesgNum.COURSE_POINT);
      coursePointMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      coursePointMesg.addField(new Field("timestamp", 1, 134, 1, 0, ""));
      field_index++;
      coursePointMesg.addField(new Field("position_lat", 2, 133, 1, 0, "semicircles"));
      field_index++;
      coursePointMesg.addField(new Field("position_long", 3, 133, 1, 0, "semicircles"));
      field_index++;
      coursePointMesg.addField(new Field("distance", 4, 134, 100, 0, "m"));
      field_index++;
      coursePointMesg.addField(new Field("type", 5, 0, 1, 0, ""));
      field_index++;
      coursePointMesg.addField(new Field("name", 6, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = coursePointMesg;
      mesg_index++;

      // workout
      field_index = 0;
      workoutMesg = new Mesg("workout", MesgNum.WORKOUT);
      workoutMesg.addField(new Field("sport", 4, 0, 1, 0, ""));
      field_index++;
      workoutMesg.addField(new Field("capabilities", 5, 140, 1, 0, ""));
      field_index++;
      workoutMesg.addField(new Field("num_valid_steps", 6, 132, 1, 0, ""));
      field_index++;
      workoutMesg.addField(new Field("wkt_name", 8, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = workoutMesg;
      mesg_index++;

      // workout_step
      field_index = 0;
      workoutStepMesg = new Mesg("workout_step", MesgNum.WORKOUT_STEP);
      workoutStepMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      workoutStepMesg.addField(new Field("wkt_step_name", 0, 7, 1, 0, ""));
      field_index++;
      workoutStepMesg.addField(new Field("duration_type", 1, 0, 1, 0, ""));
      field_index++;
      workoutStepMesg.addField(new Field("duration_value", 2, 134, 1, 0, ""));
      subfield_index = 0;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("duration_time", 134, 1000, 0, "s"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 0);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("duration_distance", 134, 100, 0, "m"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 1);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("duration_hr", 134, 1, 0, "% or bpm"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 2);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 3);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("duration_calories", 134, 1, 0, "calories"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 4);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("duration_step", 134, 1, 0, ""));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 6);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 7);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 8);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 9);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 10);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 11);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 12);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 13);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("duration_power", 134, 1, 0, "% or watts"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 14);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 15);
      subfield_index++;
      field_index++;
      workoutStepMesg.addField(new Field("target_type", 3, 0, 1, 0, ""));
      field_index++;
      workoutStepMesg.addField(new Field("target_value", 4, 134, 1, 0, ""));
      subfield_index = 0;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("target_hr_zone", 134, 1, 0, ""));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(3, 1);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("target_power_zone", 134, 1, 0, ""));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(3, 4);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("repeat_steps", 134, 1, 0, ""));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 6);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("repeat_time", 134, 1000, 0, "s"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 7);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("repeat_distance", 134, 100, 0, "m"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 8);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("repeat_calories", 134, 1, 0, "calories"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 9);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("repeat_hr", 134, 1, 0, "% or bpm"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 10);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 11);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("repeat_power", 134, 1, 0, "% or watts"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 12);
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 13);
      subfield_index++;
      field_index++;
      workoutStepMesg.addField(new Field("custom_target_value_low", 5, 134, 1, 0, ""));
      subfield_index = 0;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("custom_target_speed_low", 134, 1000, 0, "m/s"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(3, 0);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("custom_target_heart_rate_low", 134, 1, 0, "% or bpm"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(3, 1);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("custom_target_cadence_low", 134, 1, 0, "rpm"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(3, 3);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("custom_target_power_low", 134, 1, 0, "% or watts"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(3, 4);
      subfield_index++;
      field_index++;
      workoutStepMesg.addField(new Field("custom_target_value_high", 6, 134, 1, 0, ""));
      subfield_index = 0;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("custom_target_speed_high", 134, 1000, 0, "m/s"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(3, 0);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("custom_target_heart_rate_high", 134, 1, 0, "% or bpm"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(3, 1);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("custom_target_cadence_high", 134, 1, 0, "rpm"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(3, 3);
      subfield_index++;
      workoutStepMesg.fields.get(field_index).subFields.add(new SubField("custom_target_power_high", 134, 1, 0, "% or watts"));
      workoutStepMesg.fields.get(field_index).subFields.get(subfield_index).addMap(3, 4);
      subfield_index++;
      field_index++;
      workoutStepMesg.addField(new Field("intensity", 7, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = workoutStepMesg;
      mesg_index++;

      // schedule
      field_index = 0;
      scheduleMesg = new Mesg("schedule", MesgNum.SCHEDULE);
      scheduleMesg.addField(new Field("manufacturer", 0, 132, 1, 0, ""));
      field_index++;
      scheduleMesg.addField(new Field("product", 1, 132, 1, 0, ""));
      subfield_index = 0;
      scheduleMesg.fields.get(field_index).subFields.add(new SubField("garmin_product", 132, 1, 0, ""));
      scheduleMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 1);
      scheduleMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 15);
      scheduleMesg.fields.get(field_index).subFields.get(subfield_index).addMap(0, 13);
      subfield_index++;
      field_index++;
      scheduleMesg.addField(new Field("serial_number", 2, 140, 1, 0, ""));
      field_index++;
      scheduleMesg.addField(new Field("time_created", 3, 134, 1, 0, ""));
      field_index++;
      scheduleMesg.addField(new Field("completed", 4, 0, 1, 0, ""));
      field_index++;
      scheduleMesg.addField(new Field("type", 5, 0, 1, 0, ""));
      field_index++;
      scheduleMesg.addField(new Field("scheduled_time", 6, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = scheduleMesg;
      mesg_index++;

      // totals
      field_index = 0;
      totalsMesg = new Mesg("totals", MesgNum.TOTALS);
      totalsMesg.addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      totalsMesg.addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      totalsMesg.addField(new Field("timer_time", 0, 134, 1, 0, "s"));
      field_index++;
      totalsMesg.addField(new Field("distance", 1, 134, 1, 0, "m"));
      field_index++;
      totalsMesg.addField(new Field("calories", 2, 134, 1, 0, "kcal"));
      field_index++;
      totalsMesg.addField(new Field("sport", 3, 0, 1, 0, ""));
      field_index++;
      totalsMesg.addField(new Field("elapsed_time", 4, 134, 1, 0, "s"));
      field_index++;
      totalsMesg.addField(new Field("sessions", 5, 132, 1, 0, ""));
      field_index++;
      totalsMesg.addField(new Field("active_time", 6, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index] = totalsMesg;
      mesg_index++;

      // weight_scale
      field_index = 0;
      weightScaleMesg = new Mesg("weight_scale", MesgNum.WEIGHT_SCALE);
      weightScaleMesg.addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      weightScaleMesg.addField(new Field("weight", 0, 132, 100, 0, "kg"));
      field_index++;
      weightScaleMesg.addField(new Field("percent_fat", 1, 132, 100, 0, "%"));
      field_index++;
      weightScaleMesg.addField(new Field("percent_hydration", 2, 132, 100, 0, "%"));
      field_index++;
      weightScaleMesg.addField(new Field("visceral_fat_mass", 3, 132, 100, 0, "kg"));
      field_index++;
      weightScaleMesg.addField(new Field("bone_mass", 4, 132, 100, 0, "kg"));
      field_index++;
      weightScaleMesg.addField(new Field("muscle_mass", 5, 132, 100, 0, "kg"));
      field_index++;
      weightScaleMesg.addField(new Field("basal_met", 7, 132, 4, 0, "kcal/day"));
      field_index++;
      weightScaleMesg.addField(new Field("physique_rating", 8, 2, 1, 0, ""));
      field_index++;
      weightScaleMesg.addField(new Field("active_met", 9, 132, 4, 0, "kcal/day"));
      field_index++;
      weightScaleMesg.addField(new Field("metabolic_age", 10, 2, 1, 0, "years"));
      field_index++;
      weightScaleMesg.addField(new Field("visceral_fat_rating", 11, 2, 1, 0, ""));
      field_index++;
      weightScaleMesg.addField(new Field("user_profile_index", 12, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = weightScaleMesg;
      mesg_index++;

      // blood_pressure
      field_index = 0;
      bloodPressureMesg = new Mesg("blood_pressure", MesgNum.BLOOD_PRESSURE);
      bloodPressureMesg.addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      bloodPressureMesg.addField(new Field("systolic_pressure", 0, 132, 1, 0, "mmHg"));
      field_index++;
      bloodPressureMesg.addField(new Field("diastolic_pressure", 1, 132, 1, 0, "mmHg"));
      field_index++;
      bloodPressureMesg.addField(new Field("mean_arterial_pressure", 2, 132, 1, 0, "mmHg"));
      field_index++;
      bloodPressureMesg.addField(new Field("map_3_sample_mean", 3, 132, 1, 0, "mmHg"));
      field_index++;
      bloodPressureMesg.addField(new Field("map_morning_values", 4, 132, 1, 0, "mmHg"));
      field_index++;
      bloodPressureMesg.addField(new Field("map_evening_values", 5, 132, 1, 0, "mmHg"));
      field_index++;
      bloodPressureMesg.addField(new Field("heart_rate", 6, 2, 1, 0, "bpm"));
      field_index++;
      bloodPressureMesg.addField(new Field("heart_rate_type", 7, 0, 1, 0, ""));
      field_index++;
      bloodPressureMesg.addField(new Field("status", 8, 0, 1, 0, ""));
      field_index++;
      bloodPressureMesg.addField(new Field("user_profile_index", 9, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = bloodPressureMesg;
      mesg_index++;

      // monitoring_info
      field_index = 0;
      monitoringInfoMesg = new Mesg("monitoring_info", MesgNum.MONITORING_INFO);
      monitoringInfoMesg.addField(new Field("timestamp", 253, 134, 1, 0, ""));
      field_index++;
      monitoringInfoMesg.addField(new Field("local_timestamp", 0, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = monitoringInfoMesg;
      mesg_index++;

      // monitoring
      field_index = 0;
      monitoringMesg = new Mesg("monitoring", MesgNum.MONITORING);
      monitoringMesg.addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      monitoringMesg.addField(new Field("device_index", 0, 2, 1, 0, ""));
      field_index++;
      monitoringMesg.addField(new Field("calories", 1, 132, 1, 0, "kcal"));
      field_index++;
      monitoringMesg.addField(new Field("distance", 2, 134, 100, 0, "m"));
      field_index++;
      monitoringMesg.addField(new Field("cycles", 3, 134, 1, 0, "cycles"));
      field_index++;
      monitoringMesg.addField(new Field("active_time", 4, 134, 1000, 0, "s"));
      field_index++;
      monitoringMesg.addField(new Field("activity_type", 5, 0, 1, 0, ""));
      field_index++;
      monitoringMesg.addField(new Field("activity_subtype", 6, 0, 1, 0, ""));
      field_index++;
      monitoringMesg.addField(new Field("compressed_distance", 8, 132, 1, 0, "")); 
      monitoringMesg.fields.get(field_index).components.add(new FieldComponent(2, true, 16, 100, 0)); // distance
      field_index++;
      monitoringMesg.addField(new Field("compressed_cycles", 9, 132, 1, 0, "")); 
      monitoringMesg.fields.get(field_index).components.add(new FieldComponent(3, true, 16, 1, 0)); // cycles
      field_index++;
      monitoringMesg.addField(new Field("compressed_active_time", 10, 132, 1, 0, "")); 
      monitoringMesg.fields.get(field_index).components.add(new FieldComponent(4, true, 16, 1, 0)); // active_time
      field_index++;
      monitoringMesg.addField(new Field("local_timestamp", 11, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index] = monitoringMesg;
      mesg_index++;

      // pad
      field_index = 0;
      padMesg = new Mesg("pad", MesgNum.PAD);
      mesgs[mesg_index] = padMesg;
      mesg_index++;

   }
}
