//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.11 at 12:23:38 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://turtlesport.sourceforge.net/xsd/map/1/0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.turtlesport.map;
